services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: intero-php
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    ports:
      - "8000:8000"
    command: php -S 0.0.0.0:8000